// <auto-generated />
namespace Web.Datanomics.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db));
        
        string IMigrationMetadata.Id
        {
            get { return "201608140652073_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
